/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/icons.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.99, 1.13, 2.22]} rotation={[-0.91, -0.29, -0.32]} scale={1.21}>
        <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Sphere_3.geometry} material={materials['Material.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/icons.gltf')
