import { test, expect, afterAll } from 'bun:test';
import handler, { authenticated } from '../api/studio.js';
const original={BLOB_READ_WRITE_TOKEN:process.env.BLOB_READ_WRITE_TOKEN,ADMIN_PASSWORD:process.env.ADMIN_PASSWORD,SESSION_SECRET:process.env.SESSION_SECRET};
afterAll(()=>{for(const [key,value] of Object.entries(original)){if(value===undefined)delete process.env[key];else process.env[key]=value}});
function config(){process.env.BLOB_READ_WRITE_TOKEN='test-not-a-real-token';process.env.ADMIN_PASSWORD='test-only-password-with-at-least-32-characters';process.env.SESSION_SECRET='test-only-signing-key-with-at-least-32-characters'}
async function call(action,{method='POST',body={},origin='https://studio.test',cookie=''}={}){const req={method,url:'/api/studio?action='+action,query:{action},headers:{host:'studio.test',origin,cookie},socket:{remoteAddress:'127.0.0.1'},body};const res={code:200,headers:{},setHeader(k,v){this.headers[k]=v},status(c){this.code=c;return this},json(v){this.body=v;return this}};await handler(req,res);return res}
test('unconfigured publishing stays disabled',async()=>{delete process.env.BLOB_READ_WRITE_TOKEN;const r=await call('publish');expect(r.code).toBe(503);expect(authenticated({headers:{}})).toBe(false)});
test('anonymous and cross-origin mutations are blocked',async()=>{config();expect((await call('publish')).code).toBe(401);expect((await call('login',{origin:'https://attacker.test',body:{password:process.env.ADMIN_PASSWORD}})).code).toBe(403)});
test('sign-in issues a signed HttpOnly session; tampering is rejected',async()=>{config();expect((await call('login',{body:{password:'wrong'}})).code).toBe(401);const r=await call('login',{body:{password:process.env.ADMIN_PASSWORD}});expect(r.code).toBe(200);const cookie=r.headers['Set-Cookie'];expect(cookie).toContain('HttpOnly');expect(cookie).toContain('SameSite=Strict');expect(authenticated({headers:{cookie}})).toBe(true);expect(authenticated({headers:{cookie:cookie.replace(/atoz_session=./,'atoz_session=0')}})).toBe(false);expect(authenticated({headers:{cookie:'atoz_session=9999999999999.fake.fake'}})).toBe(false)});
test('invalid portfolio is rejected before storage writes',async()=>{config();const login=await call('login',{body:{password:process.env.ADMIN_PASSWORD}});const r=await call('publish',{cookie:login.headers['Set-Cookie'],body:{projects:[]}});expect(r.code).toBe(400)});
