<script>
 import { onMount, onDestroy } from 'svelte';
 import Icon from './Icon.svelte';
 import Viewer from './Viewer.svelte';
 import Guide from './Guide.svelte';
 import { validateCatalog, parseModel, checkPoster, safeAsset, MAX_MODEL_BYTES } from '../lib/catalog';
 import { loadDraft, saveDraft } from '../lib/drafts';
 export let catalog;
 export let onUpdate;
 let draft=structuredClone(catalog),index=0,assets={},urls={},status='',error='',busy=false,stats={},stored=null,configured=false,authenticated=false,password='',dirty=false;
 $: project=draft.projects[index];
 $: preview={...project,model:urls[project?.model]||project?.model,poster:urls[project?.poster]||project?.poster};
 onMount(()=>{loadDraft().then(value=>stored=value).catch(()=>status='Browser storage is unavailable. You can still export your work.');fetch('/api/studio?action=status').then(r=>r.json()).then(v=>{configured=!!v.configured;authenticated=!!v.authenticated}).catch(()=>{});const warn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)});
 onDestroy(()=>Object.values(urls).forEach(url=>URL.revokeObjectURL(url)));
 function update(key,value){draft={...draft,projects:draft.projects.map((p,i)=>i===index?{...p,[key]:value}:p)};dirty=true;status='';error='';}
 function feature(){draft={...draft,projects:draft.projects.map((p,i)=>({...p,featured:i===index}))};dirty=true}
 function add(){if(draft.projects.length>=24)return;draft={...draft,projects:[...draft.projects,{id:crypto.randomUUID(),title:'Untitled project',category:'Custom 3D',description:'Describe your model, materials and creative direction.',model:'',poster:'',featured:false,colors:false}]};index=draft.projects.length-1;dirty=true}
 function remove(){if(draft.projects.length===1||!confirm('Remove this project from the draft? Your published portfolio stays unchanged until you publish.'))return;const wasFeatured=project.featured;draft={...draft,projects:draft.projects.filter((_,i)=>i!==index)};index=Math.max(0,index-1);if(wasFeatured)feature();dirty=true}
 function move(delta){const next=index+delta;if(next<0||next>=draft.projects.length)return;const list=[...draft.projects];[list[index],list[next]]=[list[next],list[index]];draft={...draft,projects:list};index=next;dirty=true}
 async function fileChanged(event,type){const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(!file)return;error='';try{let ext;if(type==='model'){if(file.size>MAX_MODEL_BYTES)throw Error('This model exceeds 15 MB. Optimize it before uploading.');const info=parseModel(await file.arrayBuffer(),file.name);stats={...stats,[project.id]:info};ext=file.name.toLowerCase().endsWith('.glb')?'glb':'gltf';}else ext=await checkPoster(file);const path='/portfolio/custom/'+crypto.randomUUID()+'.'+ext;assets={...assets,[path]:file};urls={...urls,[path]:URL.createObjectURL(file)};update(type,path);status=type==='model'?'Model ready to preview. Save your draft to keep it.':'Poster added to the draft.';}catch(e){error=e.message}}
 async function save(){try{const valid=validateCatalog(draft);await saveDraft({catalog:valid,assets});stored={catalog:valid,assets};dirty=false;status='Draft saved on this device. Your published site has not changed.';error='';}catch(e){error=e.message}}
 function restore(){try{const value=validateCatalog(stored.catalog);if(dirty&&!confirm('Replace unsaved edits with your saved draft?'))return;Object.values(urls).forEach(url=>URL.revokeObjectURL(url));draft=value;assets=stored.assets||{};urls=Object.fromEntries(Object.entries(assets).map(([path,blob])=>[path,URL.createObjectURL(blob)]));index=0;dirty=false;status='Saved draft restored.';error='';}catch(e){error=e.message}}
 function reset(){if(!confirm('Replace this draft with the current published portfolio? Saved drafts remain available to restore.'))return;draft=structuredClone(catalog);index=0;dirty=false;error='';status='Showing the published portfolio.'}
 function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function exportFiles(){busy=true;error='';try{const valid=validateCatalog(draft);const {zipSync,strToU8}=await import('fflate');const files={'public/portfolio.json':strToU8(JSON.stringify(valid,null,2))};for(const path of new Set(valid.projects.flatMap(p=>[p.model,p.poster]).filter(p=>p.startsWith('/')))){const blob=assets[path]||await fetch(path).then(r=>{if(!r.ok)throw Error('Could not export '+path);return r.blob()});files['public'+path]=new Uint8Array(await blob.arrayBuffer());}files['HOW-TO-PUBLISH.txt']=strToU8('Copy the public folder into your AtoZ Studio project. Run bun run build and redeploy to Vercel. Existing files may be replaced. HTTPS model URLs remain external.');download(new Blob([zipSync(files,{level:0})],{type:'application/zip'}),'atoz-portfolio.zip');status='ZIP exported. Copy its public folder into this project and redeploy to publish.';}catch(e){error=e.message}finally{busy=false}}
 async function request(action,body){const r=await fetch('/api/studio?action='+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'Request failed.');return value}
 async function login(){busy=true;error='';try{await request('login',{password});authenticated=true;password='';status='Signed in. You can now publish your portfolio.';}catch(e){error=e.message}finally{busy=false}}
 async function logout(){try{await request('logout',{});authenticated=false;status='Signed out.';}catch(e){error=e.message}}
 async function publish(){busy=true;error='';try{const valid=validateCatalog(draft);const {upload}=await import('@vercel/blob/client');const replacements={};for(const path of new Set(valid.projects.flatMap(p=>[p.model,p.poster]).filter(p=>assets[p]))){status='Uploading '+path.split('/').pop()+'…';const result=await upload('atoz/assets/'+path.split('/').pop(),assets[path],{access:'public',handleUploadUrl:'/api/studio?action=upload',contentType:path.endsWith('.glb')?'model/gltf-binary':path.endsWith('.gltf')?'model/gltf+json':path.endsWith('.webp')?'image/webp':path.endsWith('.png')?'image/png':'image/jpeg'});replacements[path]=result.url;}const published={...valid,projects:valid.projects.map(p=>({...p,model:replacements[p.model]||p.model,poster:replacements[p.poster]||p.poster}))};const result=await request('publish',published);draft=result.catalog;onUpdate(result.catalog);dirty=false;status='Published. Your portfolio is updated for all visitors.';try{await saveDraft({catalog:result.catalog,assets:{}});stored={catalog:result.catalog,assets:{}};}catch{status+=' Browser draft storage is unavailable.'}}catch(e){error=e.message}finally{busy=false}}
</script>
<main class="wrap studio"><header class="panel-header"><a class="brand" href="#home">atoz<span class="brand-light">studio</span><em>.</em></a><a class="text-link" href="#home">Back to portfolio <Icon/></a></header><h1>Your work. Your space.</h1><p class="studio-intro">Manage the pieces in your portfolio. Add a textured model, choose a cover image and put your best work first.</p>
<div class="notice">{#if configured}Live publishing is available. {authenticated?'You are signed in.':'Sign in below to update the portfolio for every visitor.'}{:else}<strong>Draft mode.</strong> Changes stay on this device until you export and redeploy. Live uploads can be enabled with Vercel Blob and admin credentials; see the project README.{/if}</div>
{#if configured}<div class="login-form">{#if authenticated}<button class="button secondary" on:click={logout}>Sign out</button>{:else}<form class="login-form" on:submit|preventDefault={login}><label class="field">Admin password<input type="password" bind:value={password} autocomplete="current-password" required/></label><button class="button secondary" disabled={busy}>Sign in</button></form>{/if}</div>{/if}
<div class="panel-actions"><button class="button primary" on:click={save} disabled={busy}>Save device draft <Icon name="check"/></button><button class="button secondary" on:click={exportFiles} disabled={busy}>Export portfolio ZIP <Icon name="download"/></button>{#if authenticated}<button class="button primary" on:click={publish} disabled={busy}>Publish live <Icon/></button>{/if}{#if stored}<button class="button secondary" on:click={restore} disabled={busy}>Restore saved draft</button>{/if}<button class="button secondary" on:click={reset} disabled={busy}>Reset to published</button></div>
<div class="panel-status" role="status">{#if status}<p>{status}</p>{/if}</div>{#if error}<div class="notice error" role="alert">{error}</div>{/if}
<div class="studio-grid"><aside class="studio-sidebar" aria-label="Project library">{#each draft.projects as p,i}<button class:active={i===index} on:click={()=>index=i} aria-current={i===index?'true':undefined}>{p.title}<small>{p.featured?'★ Featured · ':''}{p.model?'3D model':'Still render'}</small></button>{/each}<button on:click={add} disabled={draft.projects.length>=24||busy}><Icon name="plus"/> Add project</button></aside>
<section class="editor" aria-label="Project editor"><h2>Edit your piece</h2><div class="form-grid"><label class="field">Project name<input value={project.title} maxlength="100" on:input={e=>update('title',e.currentTarget.value)}/></label><label class="field">Category<input value={project.category} maxlength="80" on:input={e=>update('category',e.currentTarget.value)}/></label></div><label class="field">Description<textarea value={project.description} maxlength="1000" on:input={e=>update('description',e.currentTarget.value)}></textarea></label>
<div class="form-grid"><label class="field">Upload model<input type="file" accept=".glb,.gltf" disabled={busy} on:change={e=>fileChanged(e,'model')}/><small>GLB recommended. Self-contained glTF also works. Maximum 15 MB.</small></label><label class="field">Upload cover image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} on:change={e=>fileChanged(e,'poster')}/><small>WebP recommended. PNG or JPEG accepted. Maximum 2 MB.</small></label></div>
<div class="form-grid"><label class="field">Model path or HTTPS URL<input type="text" value={project.model} placeholder="/portfolio/custom/my-model.glb" on:change={e=>update('model',e.currentTarget.value)}/><small>For hosted glTF, keep the .bin and textures beside the file and enable CORS.</small></label><label class="field">Cover image path or HTTPS URL<input type="text" value={project.poster} placeholder="/portfolio/my-cover.webp" on:change={e=>update('poster',e.currentTarget.value)}/></label></div>
<label class="checkbox-label"><input type="radio" checked={project.featured} name="featured" on:change={feature}/> Feature this piece in the hero</label><label class="checkbox-label"><input type="checkbox" checked={project.colors} on:change={e=>update('colors',e.currentTarget.checked)}/> Allow visitors to tint the first three materials</label>
{#if stats[project.id]}<div class="file-stats"><span>{stats[project.id].triangles.toLocaleString()} triangles</span><span>{stats[project.id].materials} materials</span><span>{(stats[project.id].bytes/1024/1024).toFixed(2)} MB</span></div>{#if stats[project.id].triangles>100000 || stats[project.id].bytes>5*1024*1024}<p class="notice">This model is above the mobile starting budget. Simplify the mesh, reduce texture sizes and test on a real phone before publishing.</p>{/if}{/if}
{#if safeAsset(project.model,['.glb','.gltf']) && safeAsset(project.poster,['.png','.jpg','.jpeg','.webp'])}{#key preview.model+preview.poster}<Viewer project={preview}/>{/key}{:else}<p class="notice error">Enter valid asset paths to preview this piece.</p>{/if}
<div class="editor-actions"><div class="toolbar-buttons"><button class="icon-button" disabled={index===0} on:click={()=>move(-1)}>Move up</button><button class="icon-button" disabled={index===draft.projects.length-1} on:click={()=>move(1)}>Move down</button></div><button class="icon-button danger" disabled={draft.projects.length===1||busy} on:click={remove}><Icon name="trash"/> Remove</button></div></section></div>
<section class="studio-settings"><h2>Client contact</h2><div class="form-grid"><label class="field">Email<input type="email" bind:value={draft.contact} on:input={()=>dirty=true}/></label><label class="field">WhatsApp number<input type="tel" bind:value={draft.whatsapp} on:input={()=>dirty=true}/><small>International format, digits only. Indonesia: 62 followed by the number without its first 0.</small></label></div></section>
<Guide/>
</main>
