import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
for(const name of ['draco','basis']){await mkdir('public/decoders/'+name,{recursive:true});await cp('node_modules/three/examples/jsm/libs/'+name,'public/decoders/'+name,{recursive:true});}
const catalog=JSON.parse(await readFile('public/portfolio.json','utf8'));
const source='// Generated by scripts/prepare-assets.js from public/portfolio.json.\nexport const defaultCatalog = '+JSON.stringify(catalog,null,2)+';\n';
const existing=await readFile('src/lib/defaults.js','utf8').catch(()=>null);
if(existing!==source)await writeFile('src/lib/defaults.js',source);
